name: Add to Project

  uses: skeet70/default-project-board-action@v1

with:
    # issue number, use {{ github.event.issue.number }}
    issue: {{ github.event.issue.numer }}
    # repository path, use {{ github.repository }}
    repository: {{ github.repository }}
    # project board, use the number in the slug for that board
    project: 1
    # GitHub token, use {{ secrets.GITHUB_TOKEN }}
    github_token: {{ secrets.GITHUB_TOKEN }}
    
